# Generated by Django 4.1.5 on 2023-01-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_auto_20230109_1411"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
