# Generated by Django 4.1.5 on 2023-01-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_remove_message_author_remove_message_chat_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
