# Generated by Django 4.1.5 on 2023-01-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_alter_post_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="text",
        ),
    ]
